### ISSUE TITLE
How does this compare to other open source approaches?

### ISSUE THREAD

**Issue by earth2marsh** [postman-open-technologies/openapi-componentizer#11]
I'm curious to know about how this might compare to other open source efforts:

- This open source project (disclosure, I was an advisor): https://github.com/googleinterns/spec-math
- The `join` command from the Redocly CLI: https://github.com/Redocly/redocly-cli/blob/main/docs/commands/join.md

If there were a way to find alignment across these projects, what might that look like?

**Comment by MikeRalphson** [comment]
Hi @earth2marsh ! This project was one we decided not to take forward into the final selection process for GSoC. Having looked briefly at the links you provided, I think the focus of this project is somewhat different: to identify common components / subcomponents across one or more OpenAPI definitions, extract them to a shared library document and update the `$ref`s in the source documents to match.

Postman are likely to take on this work internally, developing in the open under the Open Technologies banner.

**Comment by earth2marsh** [comment]
Aha, got it. I think I over-indexed on `taking one or more OpenAPI 3.x specifications in JSON or YAML (YAML is a superset of JSON so you can read JSON with any YAML parser) and producing the either one OpenAPI document`. 

It would be neat to have a tool to refactor common components!

**Comment by Polaris66** [comment]
> Hi @earth2marsh ! This project was one we decided not to take forward into the final selection process for GSoC. Having looked briefly at the links you provided, I think the focus of this project is somewhat different: to identify common components / subcomponents across one or more OpenAPI definitions, extract them to a shared library document and update the `$ref`s in the source documents to match.
> 
> Postman are likely to take on this work internally, developing in the open under the Open Technologies banner.

Hi @MikeRalphson , if possible I would still like to work on this project in any capacity if possible, if work is being continued. Please let me know if I can be of any help.
