### ISSUE TITLE
Print the list of objects from the spec identified by the type specified as CLI parameter

### ISSUE THREAD

**Issue by bavulapati** [postman-open-technologies/openapi-componentizer#6]
Parse an OpenAPI spec(input: URL) and print the list of objects from the spec identified by the type specified as CLI parameter.

The possible types are listed [here](https://spec.openapis.org/oas/latest.html#fixed-fields-5)
schemas
responses
parameters
examples
requestBodies
headers
securitySchemes
links
callbacks
pathItems

This is a qualifying task for GSoC'23.

**Comment by Polaris66** [comment]
Hi, Dhruv Arora this side. I was wondering if you could provide an example or a test case for the URL and type for testing purposes?

**Comment by bavulapati** [comment]
Hi @Polaris66 

**Here is an example:**
*Input url:* https://api.apis.guru/v2/specs/xkcd.com/1.0.0/openapi.yaml
*Input type:* responses
*Output:*
```
{
"200": {
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/comic"
                }
              }
            },
            "description": "OK"
          }
}
```

You can also find a variety of OpenAPI Specification on https://apis.guru to play around and experiment with.

**Comment by wldeh** [comment]
Hello @bavulapati!

Thank you for your time reviewing my response. I am excited to share my solution to the qualifying task with you.

Here is the requested script with support for both YAML and JSON input formats and handling of OpenAPI specifications from any source, including https://apis.guru/.

The script accepts two command-line parameters: -u or --url to specify the URL of the OpenAPI spec, and -t or --type to specify the type of object to print. The possible types are schemas, responses, parameters, examples, requestBodies, headers, securitySchemes, links, callbacks, and pathItems as required.

Here is an example of how to use the script using ts-node:

```ts-node parser.ts -u https://api.apis.guru/v2/specs/xkcd.com/1.0.0/openapi.yaml -t responses```
This command will parse the OpenAPI spec from the given URL and print the list of responses objects.

Here is the code for my solution:

```
import { cac } from 'cac'
import yaml from 'js-yaml'
import fetch from 'node-fetch'


/**
 * The type of the OpenAPI spec.
 */
interface OpenAPISpec {
  /**
   * The components of the OpenAPI spec.
   */
  components: {
    /**
     * The objects of the specified type.
     */
    [key: string]: any
  }
}

/**
 * The type of the command-line options.
 */
interface Options {
  /**
   * The type of object to print.
   */
  type: string
  /**
   * The URL of the OpenAPI spec.
   */
  url: string
}

// Parse command-line arguments
const cli = cac()
cli.option('-t, --type <type>', 'Type of object to print', {
  type: [String]
})
cli.option('-u, --url <url>', 'URL of the OpenAPI spec')
cli.on('parsed', (parsed) => {
  if (!parsed.options.type) {
    console.error('Error: Missing required option --type')
    cli.outputHelp()
    process.exit(1)
  }
  if (
    ![
      'schemas',
      'responses',
      'parameters',
      'examples',
      'requestBodies',
      'headers',
      'securitySchemes',
      'links',
      'callbacks',
      'pathItems'
    ].includes(parsed.options.type)
  ) {
    console.error(
      `Error: Invalid value for option --type: '${parsed.options.type}'`
    )
    cli.outputHelp()
    process.exit(1)
  }
  if (!parsed.options.url) {
    console.error('Error: Missing required option --url')
    cli.outputHelp()
    process.exit(1)
  }
})
const options = cli.parse().options as unknown as Options

// Fetch the OpenAPI spec from the URL
fetch(options.url)
  .then((res) => {
    if (!res.ok) {
      throw new Error(
        `Failed to fetch OpenAPI spec from ${options.url}: ${res.statusText}`
      )
    }
    const contentType = res.headers.get('Content-Type')
    if (contentType === 'application/json; charset=utf-8') {
      return res.json()
    } else if (contentType === 'text/yaml') {
      return res.text().then((data) => yaml.load(data))
    } else {
      throw new Error(`Unsupported Content-Type: ${contentType}`)
    }
  })
  .then((spec) => {
    // Check if the specified type exists in the spec
    if (!spec.components[options.type]) {
      throw new Error(`Type '${options.type}' not found in spec`)
    }
    // Print the list of objects of the specified type
    console.log(spec.components[options.type])
  })
  .catch((err) => console.log(err.message))
```

I hope this solution meets your requirements and I look forward to hearing your feedback.

**Comment by Polaris66** [comment]
Hello @wldeh 

Woah, you finished the task already. Nice!.

However, will this find the responses in the example given by @bavulapati  above?

**Comment by wldeh** [comment]
> Hello @wldeh
> 
> Woah, you finished the task already. Nice!.
> 
> However, will this find the responses in the example given by @bavulapati above?

Hi @Polaris66,

Thank you for your kind words and for bringing this to my attention. My solution was developed with the intention of accurately parsing an OpenAPI specification and printing the list of objects identified by the specified type within the **components object**. My approach was based on my understanding of the task description from @bavulapati, which references the URL “https://spec.openapis.org/oas/latest.html#fixed-fields-5” that describes the components object in the OpenAPI specification.

Upon reviewing bavulapati’s example, I noticed that the input type is responses, and the output shows the 200 response code with its corresponding content and description. This information is found within the paths object of the OpenAPI specification, under the specified path and operation. Given that my solution only looks for responses within the components object, it would actually not be able to find the responses shown in bavulapati’s example.

I appreciate your keen observation and am hoping bavulapati can comment on my solution and provide further clarification on whether the task is to print objects from both the components and paths objects or only from the components object that he initially referenced. I am committed to delivering high-quality work and am always open to feedback and suggestions for improvement.

Thank you once again for your valuable input.

**Comment by bavulapati** [comment]
@wldeh 🎉 Excited to see you come up with a possible solution. But as you mentioned, the example I provided differs from your approach.
To clarify, the task doesn't want the type from components object but the responses/type outside components. It doesn't harm even if it includes the type from components along with the type object outside components.

I would like you to keep the overall project in mind. The project's goal includes bring all the above mentioned possible type objects under a central location `components`. This task can be a tiny step towards that goal.

**Comment by Polaris66** [comment]
> Hi @Polaris66
> 
> **Here is an example:** _Input url:_ https://api.apis.guru/v2/specs/xkcd.com/1.0.0/openapi.yaml _Input type:_ responses _Output:_
> 
> ```
> {
> "200": {
>             "content": {
>               "*/*": {
>                 "schema": {
>                   "$ref": "#/components/schemas/comic"
>                 }
>               }
>             },
>             "description": "OK"
>           }
> }
> ```
> 
> You can also find a variety of OpenAPI Specification on https://apis.guru to play around and experiment with.

Hi, Quick Follow up question, according to the OpenAPI documentation would this be a responses or a status Code, response pair?

responses -> map[string | responseObject | referenceObject]

Hence, shouldn't the answer be:
{
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/comic"
                }
              }
            },
            "description": "OK"
}

**Comment by bavulapati** [comment]
Hey @Polaris66 

> Quick Follow up question, according to the OpenAPI documentation would this be a responses or a status Code, response pair?

As you pointed out with `responses -> map[string , responseObject | referenceObject]` , responses is a map including a string identifying the response and an object containing details about the response.

It would be difficult to identify the responses if we skip the the response code in this particular case. So, it should be a pair as provided in the example.

> Hence, do we need to add Objects existing in components or not?

No

**Comment by bavulapati** [comment]
@wldeh @Polaris66 and any interested contributors - take a look at https://community.postman.com/t/q-a-session-for-google-summer-of-code-2023-on-thursday-march-30-12pm-utc/45758
> :mega: Join the Open Source Program Office together with AsyncAPI, Collection Format and OpenAPI in this zoom session to learn how to find an API project for Google Summer of Code (GSoC) and still apply before the deadline on April 4.
:spiral_calendar:This Thursday
8am EDT
12pm UTC
1pm WAT
2pm CET
5:30pm IST
https://go.pstmn.io/gsoc-qa 

You can use this chance to know more about application process or anything about GSoC

**Comment by Polaris66** [comment]
> Hey @Polaris66 
> 
> > Quick Follow up question, according to the OpenAPI documentation would this be a responses or a status Code, response pair?
> 
> As you pointed out with `responses -> map[string , responseObject | referenceObject]` , responses is a map including a string identifying the response and an object containing details about the response.
> 
> It would be difficult to identify the responses if we skip the the response code in this particular case. So, it should be a pair as provided in the example.
> 
> > Hence, do we need to add Objects existing in components or not?
> 
> No

Hi, I figured that since we are finding common responses throughout the document it would be easier to store response Objects only and give them a common name for each one based on user's choice if not already named in Components section.

Hence, for this CLI, I figured this should be how it should work. It also applies to a lot more things which give a map from string to the particular object.

I personally think that taking the particular object would make the approach for componentizing simpler, especially because two same objects may not be given by the same name in the spec, but should refer to the same response, for example in the components.

**Comment by Polaris66** [comment]
For example, if two responses have different status code but same response Object, we would like them both to have a $ref to the same component, I think. For this, we would have to approach using each Response Object instead of a tuple.

Also, by taking the official definition of a Response Object, or a pathItem Object removes the ambiguity of using responses which could mean the tuple or a responseObject.

**Comment by bavulapati** [comment]
@Polaris66 I understand that you are thinking beyond this task but let's not complicate the task involving the identification algorithm and user input in this. We can have future PRs for them.

**Comment by Polaris66** [comment]
> @Polaris66 I understand that you are thinking beyond this task but let's not complicate the task involving the identification algorithm and user input in this. We can have future PRs for them.

The problem is that I had already coded the application to give responseObjects for responses, linkObjects for links etc. without giving the string mapping it.

And, converting it to the other version would take a lot of time. And since, the future tasks do actually require objects in such form only, I figured that it should work. The pull request I have sent right now, if asked for responses will give all objects of type responseObjects.

What do you think I should do?

**Comment by bavulapati** [comment]
@Polaris66 Try to change the implementation, while you prepare your GSoC proposal.

**Comment by bavulapati** [comment]
When reviewing all the GSoC proposals at Postman this year, we have to take into consideration that some of you might have used Artificial Intelligence like ChatGPT. While this is not against the rules for GSoC 2023, it makes it more difficult to compare project proposals to each other.
We added a paragraph regarding the topic to our [GSoC README.md](https://github.com/postman-open-technologies/gsoc-2023/blob/main/README.md) or [compontizer README.md](https://github.com/postman-open-technologies/openapi-componentizer#note-about-ai-usage) quite late, and you might not have been able to re-submit your application in time. So we want to still give you the opportunity to let us know if you have used AI for the creation of your proposal. If so, it wouldn’t disqualify you, but we would take that usage into account during evaluation.
Please let us know in your reply if you have used AI (like ChatGPT) to write your proposal or not until April 12. Thanks in advance.

**Comment by bavulapati** [comment]
Hi @Polaris66 @wldeh 

You did a great job in taking your time to understand the project OpenAPI Componentizer and coming up with great proposals. We really appreciate the energy and enthusiasm you brought to the project. Your work and the contributions in the form of PRs, community engagement lead the project till here.

@wldeh we liked the iterative approach you took in working with your PR and
@Polaris66 we are impressed with the way you took advantage of the packages out in the community

From what I understand from your GitHub profiles, @Polaris66 @wldeh are getting started with your contribution journey to the community. I was playing beach volleyball in my pre-final year of college, even without knowing that GSoC exists. You have sent proposals for GSoC!   That's no less than an achievement 🚀 . Well done! And continue your journey. We wish you all the very best.

Unfortunately, OpenAPI Componentizer has to take a halt now in the GSoC journey.
Hope you had great time with OpenAPI Componentizer!
Thanks :clap:

**Comment by wldeh** [comment]
Hello @bavulapati,

I wanted to say I really appreciate your dedication and support throughout this whole proposal process. Thank you for your kind words and encouragement! It was a pleasure to work on the OpenAPI Componentizer project with you and @Polaris66. Although this GSoC project has come to a halt, I hope I have the opportunity to work with you and the Postman community in the future. Thank you again for your time!
